### ISSUE TITLE
Connected BluePrint

### ISSUE THREAD

**Issue by charlesrg** [mmillmor/AmazonEcho-to-Vera#2]
Amazon does not have the blueprint alexa-connected-home-driver.
I believe they just updated the API's for the new: alexa-smart-home-skill-adapter
I'm running vera:  1.7.760
When using the alexa-smart-home-skill-adapter blueprint I get an error when testing:
```
START RequestId: df136ed9-13c0-11e6-9e17-1f46a366f324 Version: $LATEST
2016-05-06T19:29:40.304Z	df136ed9-13c0-11e6-9e17-1f46a366f324	*************** Parsing Error *************
2016-05-06T19:29:40.304Z	df136ed9-13c0-11e6-9e17-1f46a366f324	error parsing JSON message of type status: 
2016-05-06T19:29:40.304Z	df136ed9-13c0-11e6-9e17-1f46a366f324	*************** Parsing Error End*************
2016-05-06T19:29:40.307Z	df136ed9-13c0-11e6-9e17-1f46a366f324	TypeError: Cannot read property 'devices' of undefined
    at /var/task/index.js:83:32
    at /var/task/index.js:467:9
    at IncomingMessage.<anonymous> (/var/task/index.js:526:40)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
END RequestId: df136ed9-13c0-11e6-9e17-1f46a366f324
REPORT RequestId: df136ed9-13c0-11e6-9e17-1f46a366f324	Duration: 2401.73 ms	Billed Duration: 2500 ms 	Memory Size: 512 MB	Max Memory Used: 18 MB	
Process exited before completing request
```

Please let me know if you have some light into this.

**Comment by mmillmor** [comment]
Closed. This was code for V1, not V2.
